development:
  host: localhost
  port: 5433
  adapter: postgresql
  encoding: unicode
  database: Src_development
  pool: 5
  username: postgres
  password: masterkey

test:
  adapter: postgresql
  encoding: unicode
  database: Src_test
  pool: 5
  username: postgres
  password: masterkey

production:
  adapter: postgresql
  encoding: unicode
  database: Src_production
  pool: 5
  username: postgres
  password: masterkey
